import type { Metadata } from 'next';
import { alternates } from '@/lib/i18n';
import { ArticlePage } from '@/components/ArticlePage';
import { CompatibilityTable } from '@/components/CompatibilityTable';
export const metadata: Metadata = { title: 'Compatibility', alternates: alternates('en', '/compatibility/') };
export default function Page() { return <ArticlePage locale="en" title="Verified means actually verified." lead="Updated October 6, 2026. Anything not tested on real hardware isn’t called supported."><CompatibilityTable locale="en"/>
<h2>How it was verified</h2><p>On a Mac with Apple silicon running macOS 27.2, with a 2 TB USB NTFS drive: automatic write access on connect; saving from Finder and TextEdit; writing a 1 GB file and hundreds of small files; automatic recovery after forced interruptions mid-write and after unplugging during a copy; and staying writable through sleep and wake. All files, permissions, and the disk check were then confirmed in Windows 11 before continuing to edit on the Mac. Separately, on disposable disk images, every write step was made to fail or be interrupted one at a time—more than 700 checks in all. On a clean install of macOS 26.6, the notarized release installer was used for installation and setup, and reading, writing, and interruption recovery were checked on a disk image.</p>
<h2>How the 0.5.1 write speedup was verified</h2><p>Writes to free space no longer back up the old contents first. On disposable disk images, every write step was made to fail or be interrupted one at a time (720 checks), and the installed extension was force-quit mid-write; each time the disk rolled back to its last consistent point with existing data intact. On a 2 TB USB drive, a 1 GB file wrote at about 42 MB/s and matched byte for byte. Since 0.5.5, writes from about the last 20 seconds are rolled back after an unplug: on a real drive, a file copied 30 seconds before unplugging was complete, and after unplugging mid-copy the part already written matched the original byte for byte, with no stale data.</p>
<h2>How BitLocker was verified</h2><p>Four BitLocker volumes were created in Windows 11 Pro (XTS-AES 128/256 and AES-CBC 128/256) and unlocked with both the password and the recovery key. Files with Chinese names and a large file matched the checksums computed in Windows byte for byte. For writing, an image of each method went through 26 interruption cases (power loss at any write, torn writes, crashes, a drive cache losing data); every recovery left a clean volume with existing files intact, and without the key recovery refused and wrote nothing. On real hardware, Windows 11 created and encrypted an 812 MB partition (XTS-AES 128) on a 2 TB USB drive; on macOS 27.2 a 100 MB file was written (about 31 MB/s), folders with Chinese names created, files changed, renamed and deleted; after a killed process and a real unplug it rolled back on its own; back in Windows it unlocked with the password, disk check found no problems and every checksum matched. A disk marked as needing a check opened read-only.</p>
<h2>How 0.7.0 was verified</h2><p>On both a regular NTFS partition and a BitLocker partition of a 2 TB USB drive (macOS 27.2), 12 everyday operations passed: renaming and moving non-empty folders, case-only renames, moving between folders, deleting whole folders, the “write a new file, then replace” save that apps use, names with characters Windows doesn’t allow such as ? : *, git commits and merges, extracting source code and comparing every file, rsync, symbolic links, extended attributes, and ditto copies. Saving 37 times in a row through the system document-saving interface (the same path Pages and TextEdit use for documents saved as folders, such as .rtfd) matched file for file. A 1 GB file wrote at about 51–57 MB/s and read at about 100 MB/s, byte for byte; a folder of 12,000 files listed in about 0.2 s; deleting 600 files took about 0.5 s. On disposable disk images, more than 1,400 write-journal checks and 15 NTFS engine test suites passed, and the engine tests also ran clean under memory-checking tools.</p>
<h2>Not covered yet</h2><ul><li>Whole USB drives encrypted directly in Windows (including drives with 4K sectors).</li><li>Physical USB drives on macOS 26, other macOS versions, and Intel-based Macs.</li><li>Clicking Save in Pages and Keynote themselves (the same path as the system document-saving interface that was tested).</li><li>Whether unplugging and reconnecting can stand in for a restart after the file system extension quits unexpectedly.</li><li>Writing to several regular NTFS disks at once (the second gets write access automatically after the first is ejected); one regular NTFS disk plus one BitLocker disk can be written at the same time, tested.</li><li>Writing compressed, sparse, or encrypted files and reparse points.</li></ul>
<h2>Known limitations</h2><ul><li>If Volisle’s file system extension quits unexpectedly (a crash, or macOS ends it), the disk can’t be read, written, or ejected until you restart your Mac. After restarting, connect it again: it returns to its last consistent state, and changes from about the last 20 seconds before the extension quit are undone. Volisle tells you when this happens.</li><li>On the Mac you can still create a file whose name differs only in letter case from an existing one (README next to Readme); Windows can open only one of them. Creating a folder or renaming to such a name says the name is already taken.</li><li>BitLocker’s Windows 7 default, “AES with Diffuser”, isn’t supported.</li></ul>
<p className="notice">Volisle doesn’t delete the Windows hibernation file, force an eject, or repair disks. A “needs checking” flag is cleared only when you choose “Check on This Mac” and the read-only check finds nothing wrong. Erasing a disk deletes all of its data. Keep backups of important data.</p>
</ArticlePage>; }
