import type { Metadata } from 'next';
import { alternates } from '@/lib/i18n';
import { ArticlePage } from '@/components/ArticlePage';
import { CompatibilityTable } from '@/components/CompatibilityTable';
export const metadata: Metadata = { title: 'Compatibility', alternates: alternates('en', '/compatibility/') };
export default function Page() { return <ArticlePage locale="en" title="Verified means actually verified." lead="Updated October 3, 2026. Anything not tested on real hardware isn’t called supported."><CompatibilityTable locale="en"/>
<h2>How it was verified</h2><p>On a Mac with Apple silicon running macOS 27.2, with a 2 TB USB NTFS drive: automatic write access on connect; saving from Finder and TextEdit; writing a 1 GB file and hundreds of small files; automatic recovery after forced interruptions mid-write and after unplugging during a copy; and staying writable through sleep and wake. All files, permissions, and the disk check were then confirmed in Windows 11 before continuing to edit on the Mac. Separately, on disposable disk images, every write step was made to fail or be interrupted one at a time—more than 700 checks in all. On a clean install of macOS 26.6, the notarized release installer was used for installation and setup, and reading, writing, and interruption recovery were checked on a disk image.</p>
<h2>How the 0.5.1 write speedup was verified</h2><p>Writes to free space no longer back up the old contents first. On disposable disk images, every write step was made to fail or be interrupted one at a time (720 checks), and the installed extension was force-quit mid-write; each time the disk rolled back to its last consistent point with existing data intact. On a 2 TB USB drive, a 1 GB file wrote at about 42 MB/s and matched byte for byte. A physical unplug test during a copy with the new method is still to be done.</p>
<h2>How BitLocker was verified</h2><p>Four BitLocker volumes were created in Windows 11 Pro (XTS-AES 128/256 and AES-CBC 128/256) and unlocked with both the password and the recovery key. Files with Chinese names and a large file matched the checksums computed in Windows byte for byte. For writing, an image of each method went through 26 interruption cases (power loss at any write, torn writes, crashes, a drive cache losing data); every recovery left a clean volume with existing files intact, and without the key recovery refused and wrote nothing. On real hardware, Windows 11 created and encrypted an 812 MB partition (XTS-AES 128) on a 2 TB USB drive; on macOS 27.2 a 100 MB file was written (about 31 MB/s), folders with Chinese names created, files changed, renamed and deleted; after a killed process and a real unplug it rolled back on its own; back in Windows it unlocked with the password, disk check found no problems and every checksum matched. A disk marked as needing a check opened read-only.</p>
<h2>Not covered yet</h2><ul><li>Whole USB drives encrypted directly in Windows (including drives with 4K sectors).</li><li>Physical USB drives on macOS 26, other macOS versions, and Intel-based Macs.</li><li>Overwriting documents that are saved as folders.</li><li>Writing to several regular NTFS disks at once (the second gets write access automatically after the first is ejected); one regular NTFS disk plus one BitLocker disk can be written at the same time, tested.</li><li>Writing compressed, sparse, or encrypted files and reparse points.</li></ul>
<p className="notice">Volisle doesn’t delete the Windows hibernation file, force an eject, or repair disks. A “needs checking” flag is cleared only when you choose “Check on This Mac” and the read-only check finds nothing wrong. Erasing a disk deletes all of its data. Keep backups of important data.</p>
</ArticlePage>; }
